version: '3'
services:
  opensearch:
    image: opensearch_icu:latest
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 19200:9200
      - 19600:9600
    networks:
      - elephant-net

  elephant-opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.19.0
    ports:
      - 15601:5601
    expose:
      - "15601"
    depends_on:
      - opensearch
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - elephant-net

  database:
    image: 'postgres:17.5'
    ports:
      - 15432:5432
    expose:
      - "15432"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
    networks:
      - elephant-net
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15480:80
    expose:
      - "15480"
    environment:
      - PGADMIN_DEFAULT_EMAIL=demo@ecms.se
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
    depends_on:
      - database
    networks:
      - elephant-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    command:
      - server
      - /data
      - --console-address
      - :9001
    ports:
      - 19000:9000
      - 19001:9001
    expose:
      - "19001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - elephant-net
    volumes:
      - minio-data:/data

  redis:
    image: redis:6.2-alpine
    ports:
      - 16379:6379
    expose:
      - "16379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - elephant-net
    volumes: 
      - redis-data:/data
      
  elsinod:
    image: ghcr.io/ttab/elsinod:v0.0.0
    restart: on-failure
    ports:
      - 7080:1080
      - 7081:1081
    expose:
      - "7080"
    environment:
      - CONN_STRING=postgres://postgres:${PASSWORD}@elephant-database/postgres
      - CLIENT_SECRET=${PASSWORD}
      - DEMO_PASSWORD=${PASSWORD}
      - PUBLIC_URL=http://localhost:7080
      - INTERNAL_URL=http://elsinod:1080
    networks:
      - elephant-net
      
  repository:
    image: ghcr.io/ttab/elephant-repository:v1.1.2
    restart: on-failure
    depends_on:
      - minio
      - database
    environment:
      - LOG_LEVEL=DEBUG
      - S3_ENDPOINT=http://minio:9000/
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_ACCESS_KEY_SECRET=minioadmin
      - CONN_STRING=postgres://postgres:${PASSWORD}@database/elephant-repository
      - OIDC_CONFIG=http://elsinod:1080/.well-known/openid-configuration
      - CORS_HOSTS=localhost
      - NO_EVENTSINK=true
    ports:
      - 1080:1080
      - 1081:1081
    expose:
      - "1080"
    networks:
      - elephant-net

  index:
    image: ghcr.io/ttab/elephant-index:v1.0.11-pre
    restart: on-failure
    depends_on:
      - repository
      - database
      - opensearch
      - elsinod
    environment:
      - LOG_LEVEL=DEBUG
      - S3_ENDPOINT=http://minio:9000/
      - REPOSITORY_ENDPOINT=http://repository:1080
      - OPENSEARCH_ENDPOINT=http://opensearch:9200
      - MANAGED_OPENSEARCH=false
      - SHARDING_POLICY=:1:0
      - CONN_STRING=postgres://postgres:${PASSWORD}@database/elephant-index
      - OIDC_CONFIG=http://elsinod:1080/.well-known/openid-configuration
      - CLIENT_ID=indexer
      - CLIENT_SECRET=${PASSWORD}
      - CORS_HOSTS=localhost
      - NO_EVENTSINK=true
      - DEFAULT_LANGUAGE=sv-se
    ports:
      - 2080:1080
      - 2081:1081
    expose:
      - "2080"
    networks:
      - elephant-net

  docbrowser:
    image: ghcr.io/ttab/docbrowser:v0.2.8
    restart: on-failure
    depends_on:
      - repository
      - index
      - elsinod
    environment:
      - REPO_ENDPOINT=http://repository:1080
      - INDEX_ENDPOINT=http://index:1080
      - OIDC_PROVIDER=http://elsinod:1080/
      - CLIENT_ID=docbrowser
      - CLIENT_SECRET=${PASSWORD}
      - CHROME_ENDPOINT=https://stage.tt.se/elephant/
      - CALLBACK_URL=http://localhost:3080/auth/callback
    ports:
      - 3080:1080
      - 3081:1081
    expose:
      - "3080"
    networks:
      - elephant-net

  chrome:
    image: ghcr.io/ttab/elephant-chrome:v1.4.1
    restart: on-failure
    depends_on:
      - repository
      - index
      - redis
      - elsinod
    ports:
      - 4080:5183
    expose:
      - "4080"
    networks:
      - elephant-net
    environment:
      - AUTH_SECRET=Cdf/liGxRfubPApstGAsc5mecGfXotyMaRhHLD7Jje9l0=
      - AUTH_KEYCLOAK_ID=elephant
      - AUTH_KEYCLOAK_SECRET=E1C8qBMffW1QaDT4GlwuM3YoE5rT8Bib
      - AUTH_KEYCLOAK_ISSUER=http://localhost:7080
      - AUTH_TRUST_HOST=http://localhost:4080
      - WS_URL=http://localhost:4080
      - AUTH_KEYCLOAK_IDP_HINT=saml
      - REPOSITORY_URL=http://repository:1080
      - INDEX_URL=http://index:1080
      - SPELLCHECK_URL=http://spell:1080
      - CONTENT_API_URL=http://api.stage.tt.se
      - USER_URL=http://user:1080
      - REDIS_URL=redis://redis:6379
      - PROTOCOL=http
      - HOST=localhost
      - PORT=4080
      - BASE_URL=/elephant
      - ELEPHANT_CHROME_CLIENT_ID=elephant-chrome
      - ELEPHANT_CHROME_CLIENT_SECRET=MTVmY2YxNjg3YTE0NDEwZTAzZTY0NTI1
      

volumes:
  opensearch-data:
  postgresql-data:
  pgadmin-data:
  redis-data:
  minio-data:

networks:
  elephant-net:
