// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import ()

type SchemaVersion struct {
	Version int32
}

type SigningKey struct {
	ID   string
	Data []byte
}
