// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package postgres

import (
	"context"
)

const addSigningKey = `-- name: AddSigningKey :exec
INSERT INTO signing_key(id, data)
VALUES($1, $2)
`

type AddSigningKeyParams struct {
	ID   string
	Data []byte
}

func (q *Queries) AddSigningKey(ctx context.Context, arg AddSigningKeyParams) error {
	_, err := q.db.Exec(ctx, addSigningKey, arg.ID, arg.Data)
	return err
}

const getSigningKeys = `-- name: GetSigningKeys :many
SELECT id, data FROM signing_key
WHERE id != ANY($1::text[])
`

func (q *Queries) GetSigningKeys(ctx context.Context, known []string) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, getSigningKeys, known)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(&i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
