name: Build

on:
  push:
    tags:
      - helm-*

jobs:
  build:
    name: Create Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Helm
        uses: azure/setup-helm@v4.3.1

      - name: Login to registry
        run: |
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} oci://ghcr.io

      - name: Package and push
        run: |
          VERSION=$(echo ${{ github.ref_name }} | awk -F- '{print $2}')
          helm dependency build ./chart
          helm package ./chart
          helm push elsinod-$VERSION.tgz oci://ghcr.io/${{ github.repository }}
